version: "3.8"

services:
  dash-server:
    build: ./dash-server
    ports:
      - "3000:3000"
    networks:
      - dash-network
    cap_add:
      - NET_ADMIN  # Ajoute les privilèges réseau
    privileged: true  # <-- Ajoute cette ligne

  dash-client:
    build: ./dash-client
    ports:
      - "5173:5173"
    networks:
      - dash-network
    cap_add:
      - NET_ADMIN  # Ajoute les privilèges réseau
    privileged: true  # <-- Ajoute cette ligne
    depends_on:
      - dash-server

networks:
  dash-network:
    driver: bridge
